// © SS220, MIT full text: https://raw.githubusercontent.com/SerbiaStrong-220/space-station-14/master/MIT_LICENSE.TXT

using Content.Client.Stylesheets;
using Content.Client.UserInterface.Controls;
using Content.Shared.Power.EntitySystems;
using Content.Shared.PowerCell;
using Content.Shared.Silicons.Borgs.Components;
using Content.Shared.SS220.SiliconComponents;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.SS220.Silicon.UI;

[GenerateTypedNameReferences]
public sealed partial class SiliconComponentsMenu : FancyWindow
{
    [Dependency] private IEntityManager _entity = default!;
    private PowerCellSystem _powerCell;
    private SharedBatterySystem _battery;

    public Action? OpticsTextureButtonPressed;
    public Action? ServoTextureButtonPressed;
    public Action? BrainTextureButtonPressed;
    public Action? SpineTextureButtonPressed;
    public Action? DriveTextureButtonPressed;
    public Action? EjectBatteryTextureButtonPressed;
    public Action<EntityUid>? RemoveModuleTextureButtonPressed;

    private List<EntityUid> _modules = new();

    public EntityUid Entity;

    public SiliconComponentsMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TextureButtonDict[PartType.Brain] = BrainTextureButton;
        TextureButtonDict[PartType.Drive] = DriveTextureButton;
        TextureButtonDict[PartType.Optics] = OpticsTextureButton;
        TextureButtonDict[PartType.Spine] = SpineTextureButton;
        TextureButtonDict[PartType.Servo] = ServoTextureButton;

        _powerCell = _entity.System<PowerCellSystem>();
        _battery = _entity.System<SharedBatterySystem>();

        EjectBatteryTextureButton.OnPressed += _ => EjectBatteryTextureButtonPressed?.Invoke();
        OpticsTextureButton.OnPressed += _ => OpticsTextureButtonPressed?.Invoke();
        ServoTextureButton.OnPressed += _ => ServoTextureButtonPressed?.Invoke();
        BrainTextureButton.OnPressed += _ => BrainTextureButtonPressed?.Invoke();
        SpineTextureButton.OnPressed += _ => SpineTextureButtonPressed?.Invoke();
        DriveTextureButton.OnPressed += _ => DriveTextureButtonPressed?.Invoke();
    }

    public readonly Dictionary<PartType, TextureButton> TextureButtonDict = new Dictionary<PartType, TextureButton>();

    public void SetEntity(EntityUid entity)
    {
        Entity = entity;

        UpdateBatteryTextureButton();
        UpdateTextureButtons();
        UpdateModulePanel();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var chargeFraction = 0f;

        if (_powerCell.TryGetBatteryFromSlot(Entity, out var battery))
            chargeFraction = _battery.GetCharge(battery.Value.AsNullable()) / battery.Value.Comp.MaxCharge;

        ChargeBar.Value = chargeFraction;
        ChargeLabel.Text = Loc.GetString("borg-ui-charge-label",
            ("charge", (int)MathF.Round(chargeFraction * 100)));
    }

    public void UpdateBatteryTextureButton()
    {
        EjectBatteryTextureButton.Disabled = !_powerCell.HasBattery(Entity);
    }

    public void UpdateTextureButtons()
    {
        if (!_entity.TryGetComponent(Entity, out SiliconComponentsComponent? comp))
            return;

        foreach (var TextureButton in TextureButtonDict.Keys)
        {
            SpriteView? TextureButtonView = null;

            foreach (var child in TextureButtonDict[TextureButton].Children)
            {
                if (child is SpriteView childView)
                {
                    TextureButtonView = childView;
                    break;
                }
            }

            if (TextureButtonView == null)
                return;

            if (TextureButtonDict[TextureButton] == null)
                continue;

            if (comp.Parts.TryGetValue(TextureButton, out var part) && part.ContainedEntity is { Valid: true } partValid)
            {
                TextureButtonDict[TextureButton].Text = _entity.GetComponent<MetaDataComponent>(partValid).EntityName;

                TextureButtonView.SetEntity(partValid);
                TextureButtonView.Visible = true;

                continue;
            }

            TextureButtonView.Visible = false;
            TextureButtonDict[TextureButton].RemoveStyleClass(StyleClass.TextureButtonOpenLeft);
        }
    }

    public void UpdateModulePanel()
    {
        if (!_entity.TryGetComponent(Entity, out BorgChassisComponent? chassis))
            return;

        ModuleCounter.Text = Loc.GetString("borg-ui-module-counter",
            ("actual", chassis.ModuleCount),
            ("max", chassis.MaxModules));

        if (chassis.ModuleContainer.Count == _modules.Count)
        {
            var isSame = true;
            foreach (var module in chassis.ModuleContainer.ContainedEntities)
            {
                if (_modules.Contains(module))
                    continue;
                isSame = false;
                break;
            }

            if (isSame)
                return;
        }

        ModuleContainer.Children.Clear();
        _modules.Clear();
        foreach (var module in chassis.ModuleContainer.ContainedEntities)
        {
            var moduleComponent = _entity.GetComponent<BorgModuleComponent>(module);
            var control = new SiliconModuleControl(module, _entity, !moduleComponent.DefaultModule);
            control.RemoveTextureButtonPressed += () =>
            {
                RemoveModuleTextureButtonPressed?.Invoke(module);
            };
            ModuleContainer.AddChild(control);
            _modules.Add(module);
        }
    }
}
