using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.SS220.Silicon.UI;

[GenerateTypedNameReferences]
public sealed partial class SiliconModuleControl : PanelContainer
{
    public Action? RemoveTextureButtonPressed;

    public SiliconModuleControl(EntityUid entity, IEntityManager entityManager, bool canRemove)
    {
        RobustXamlLoader.Load(this);

        ModuleView.SetEntity(entity);
        ModuleName.Text = entityManager.GetComponent<MetaDataComponent>(entity).EntityName;
        RemoveTextureButton.TexturePath = "/Textures/Interface/Nano/cross.svg.png";
        RemoveTextureButton.OnPressed += _ =>
        {
            RemoveTextureButtonPressed?.Invoke();
        };
        RemoveTextureButton.Visible = canRemove;
    }
}

